### ISSUE TITLE
Any way to get a built iOS release?

### ISSUE THREAD

**Issue by aksel** [giellalt/keyboard-fao#1]
Would you consider including Faroese in the dev Divvun Keyboards app? Normally I'd try to build it myself, but I switched to iPhone yesterday, and have never had an Apple laptop, so I'm not sure I'm able to build it, let alone how I'd go about installing it.

If including it is out of the question, do you have some pointers on how I'd build it myself?

Some context:

I'm a bit frustrated with the multilingual typing UX on iOS, and have been spending all evening looking into my options. Coming up short, I sadly reinstalled GBoard, which never worked well for me in the first place. But turns out, it doesn't support Faroese on iOS 😅

And now, somehow, I have stumbled upon this repo, which is *exactly* what I've been searching for all evening.

I must say, I'm astonished by your work. Warms my heart to have found this, to see your efforts in aiding Faroese. And then further amazed by the scope of these projects, absolutely amazing. Beautiful. Thank you ❤️

**Comment by snomos** [comment]
Hello and welcome! Thanks so very much for the nice words 🙂 

The Faroese keyboard is already included in the released version of the Divvun Dev Keyboards app: https://apps.apple.com/us/app/divvun-dev-keyboards/id1518256662

After installing the app, you need to enable the keyboard in the System settings app, most easily in **Divvun Dev Keyboards > Keyboards**. You should also grant full access to the keyboard - we do not collect any data, so it is safe to enable it. It does collect data for automatic creation of a user dictionary, but everything stays on the phone, and you can review and edit the collected data via the app itself.

We are working on an update to the keyboard apps, mainly focusing on improving the quality on iPads, and adding a few more languages. A beta release will come soon, and the public release a bit later.

By the way, Apple does provide a Faroese keyboard of their own making in iOS. It does not include a speller or any other support beyond the actual keyboard, though.

Feel free to submit other issues or pull requests - anything! 🙂

**Comment by aksel** [comment]
I didn't see that you replied - thanks!
